; RocketFlightComputer — PlatformIO project
; Board: Custom MIMXRT1062, programmed as Teensy 4.1

[env:teensy41]
platform  = teensy
board     = teensy41
framework = arduino

lib_deps =
    adafruit/Adafruit BNO08x@^1.2.3
    adafruit/Adafruit BMP3XX Library@^2.1.4
    adafruit/Adafruit ADXL375@^1.0.1
    adafruit/Adafruit INA260 Library@^1.5.0
    mikalhart/TinyGPSPlus@^1.0.3

build_flags =
    -DTEENSY41
    -O2

monitor_speed = 115200
